### ISSUE TITLE
Does not work in this case

### ISSUE THREAD

**Issue by harryqt** [TheDragonCode/laravel-json-response#23]
![image](https://user-images.githubusercontent.com/18257605/178250578-92cace3d-af4c-429f-8c38-3025b877da92.png)

![image](https://user-images.githubusercontent.com/18257605/178250740-bea42941-100d-46e1-8745-5a3837fe6d01.png)

**Comment by harryqt** [comment]
This trick actually worked: https://stackoverflow.com/a/70147317/2277053

**Comment by andrey-helldar** [comment]
Perhaps auto-discover is disabled in your application, or `dragon-code/laravel-json-response` is added to exclusions:

```json
"extra": {
    "laravel": {
        "dont-discover": [
            "dragon-code/laravel-json-response"
        ]
    }
},
```

I added [tests](https://github.com/TheDragonCode/laravel-json-response/blob/main/tests/Middlewares/SetHeaderMiddlewareTest.php#L50-L58) to redefine the `*/*` header and they [passed](https://github.com/TheDragonCode/laravel-json-response/actions/runs/2650960932).

Either your application does not use the [SetHeaderMiddleware](https://github.com/TheDragonCode/laravel-json-response/blob/main/src/Middlewares/SetHeaderMiddleware.php) middleware. Try diagnosing the problem by adding, for example, a call to `Log::info` in the middleware.
